language: java
jdk: oraclejdk11
os:
- linux
services: 
- mongodb
script: 
  for PROJECT_DIR in */
  do 
    cd $PROJECT_DIR
    for TASK_DIR in */
    do
        cd $TASK_DIR
        if [[ -f "gradlew" ]]
        then
            ./gradlew check
        fi
        cd ..
    done
    cd ..
  done
notifications:
    email: false